### ISSUE TITLE
Running "theia build" in hello-world-extension project browser-app folder breaks it all

### ISSUE THREAD

**Issue by vince-fugnitto** [theia-ide/generator-theia-extension#36] opened 2019-05-27 10:29 UTC
Transfer of the issue https://github.com/theia-ide/theia/issues/5182

**Comment by JonasHelming** [comment] 2020-02-22 11:46
I cannot reproduce this, suggest to close the ticket.

**Comment by JonasHelming** [comment] 2020-04-20 09:25
BTW, I tested the reproduction steps in the [original ticket](https://github.com/eclipse-theia/theia/issues/5182) (see below), it works fine for me, I think we should close this.

Reproduction

Execute the steps in the tutorial

yo theia-extension hello-world-extension
let it finish , which will run "yarn prepare" script from root of the workspace
cd browser-app
yarn start
Check for Hello Menu item in localhost:3000 and its there
Stop the server CTRL-C
still in browser-app, do "yarn prepare" which will run theia build
When it's finished do "yarn start"
Go to localhost:3000 and there is no sign of Hello menu item. No errors.

**Comment by JonasHelming** [comment] 2020-04-20 12:23
@vince-fugnitto

**Closed** 2020-04-20 12:28 UTC
Labels: bug
